#pragma once

// Lua helper to link Lua with our C++/Game

#include <string>
#include <functional>
#include <map>
#include <SimpleMath.h>

// Required Lua libraries
extern "C"
{
#include "../lua-5.4.4/include/lua.h"
#include "../lua-5.4.4/include/lauxlib.h"
#include "../lua-5.4.4/include/lualib.h"
}

#ifdef _WIN32
#pragma comment(lib, "../lua-5.4.4/liblua54.a")
#endif // WIN32

// LuaOK function: Checks Lua stack operation results and handles errors.
bool LuaOK(lua_State* L, int id);

// ******FUNCTIONS******

// CallVoidVoidCFunc function: Calls a Lua function by name with no parameters or return values.
void CallVoidVoidCFunc(lua_State* L, const std::string& fName);
// CallVoidVoidCFunc function: Calls a Lua function by name, passing a single float parameter.
void CallVoidVoidCFunc(lua_State* L, const std::string& fName, float number);

// LuaFRandomNum function: Returns a random number generated by a Lua function within a specified range.
float LuaFRandomNum(lua_State* L, const std::string& fName, float min, float max);

// LuaFLerpNum function: Returns a value interpolated by a Lua function between two floats over a parameter.
float LuaFLerpNum(lua_State* L, const std::string& fName, float a, float b, float t);

// LuaUpdateMusicVol function: Allows a Lua function to update the music volume across the game.
int LuaUpdateMusicVol(lua_State* L);
// LuaAdjustMasterVol function: Allows a Lua function to adjust the master volume across the game.
int LuaAdjustMasterVol(lua_State* L);
// LuaAdjustMusicVol function: Allows a Lua function to adjust the music volume across the game.
int LuaAdjustMusicVol(lua_State* L);
// LuaAdjustGameVol function: Allows a Lua function to adjust the game volume across the game.
int LuaAdjustGameVol(lua_State* L);

// ******VARIABLES*******

// LuaGetInt function: Returns an integer from a Lua script based on the variable name.
int LuaGetInt(lua_State* L, const std::string& name);

// LuaGetNum function: Returns a float from a Lua script based on the variable name.
float LuaGetNum(lua_State* L, const std::string& name);

// LuaGetStr function: Returns a string from a Lua script based on the variable name.
std::string LuaGetStr(lua_State* L, const std::string& name);

// LuaGetVec2 function: Returns a DirectX::SimpleMath::Vector2 from a Lua script based on the variable name.
DirectX::SimpleMath::Vector2 LuaGetVec2(lua_State* L, const std::string& name);